### ISSUE TITLE
Can't receive message on iOS

### ISSUE THREAD

**Issue by xnog** [Raudius/Pushraven#1]
Hello, I created a firebase account and I am trying to send notifications to both (Android and iOS devices) but only Android is working. Is there any special step to work on iOS too?

**Comment by Raudius** [comment]
Are you able to send notifications to iOS from the firebase console?

https://firebase.google.com/docs/notifications/ios/console-device#send_a_message_from_the_notifications_console

**Comment by xnog** [comment]
Yes, from firebase console it worked.
I found a way that was setting priority to 10 and it worked.
Thanks.
