### ISSUE TITLE
push() call doesn't send HTTP request if response is not processed properly

### ISSUE THREAD

**Issue by ivankashtanov** [Raudius/Pushraven#10]
Hi,

I've encountered a bug when using your library.

After notification is properly set up, calling `FcmResponse resp = Pushraven.push(myNotification)` doesn't actually send HTTP request to Firebase server. You have to call `resp.getResponseCode()` or `resp.toString()` afterwards for it to be sent.
The issue is described [here](https://stackoverflow.com/questions/34596975/why-does-httpurlconnection-not-send-the-http-request) and is caused by the way  sending is implemented in `Http(s)URLConnection` class.

Please add explicit call of e.g. `getResponseCode` method after calling `connect` [here](https://github.com/Raudius/Pushraven/blob/master/Pushraven/src/us/raudi/pushraven/Pushraven.java#L80), probably in `FcmResponse` constructor.
If adding it is not OK for some reason, please add info about this to README.

**Comment by Raudius** [comment]
Thanks,

This got broken in the latest release (less than a week ago). Thanks for pointing it out so quickly.

It should be fixed now. It is released as version 1.0.2 in maven and also in the release section in Github.
