### ISSUE TITLE
Notifications not sent from Google App Engine backend

### ISSUE THREAD

**Issue by lmgagne** [Raudius/Pushraven#11]
Hello,

How can you see whether or not the message was sent and acknowledged properly? The integration works as we are able to send messages directly from the firebase messaging page. However, we do not get any messaging while trying to send messages from the backend (based on Google App Engine). 

How can we troubleshoot this? Is the only way to get this info through Google Play Console? If so, is it mandatory to publish the app or there is any other way around?

Thanks.

**Comment by Raudius** [comment]
Can you confirm that you are using version 1.0.2?

There was an issue with version 1.0.1 where notifications were not sent correctly.

**Comment by lmgagne** [comment]
Confirmed. Is there anything to be done in firebase or play store?

**Comment by Raudius** [comment]
I will look into the issue this coming week.  Could you perhaps post some code showing how you are sending the notification through Pushraven  so I can try to replicate the issue?

**Comment by lmgagne** [comment]
In a nutshell, our backend is based on GCP App Engine.
One of our method sends a notification back to the user/mobile phone.

We've been testing reception of notifications using firebase testing
capabilities with no issue.
Where can we see whether the message has be sent successfully or not?

Here is our code:

Pushraven.setKey(<*server key found under firebase/messaging*>);

Notification raven = new Notification();
raven.to(user.getFcmToken());
raven.addNotificationAttribute("data", "test");

Pushraven.setNotification(raven);
Pushraven.push();

**Comment by Raudius** [comment]
That should work.

I believe you should be able to check through the firebase console what messages have gotten through to the API. If they appear on the console then you should check if the notifications reception is being handled correctly. Otherwise it could very well be an issue with Pushraven and I will investigate further.

**Comment by lmgagne** [comment]
This is it... I do not see messages coming in.
This snippet of code does not throw any error.

**Comment by Raudius** [comment]
I am still not sure what the issue is. Can you print out the response you get from the push? 

System.out.println( Pushraven.push() );

**Comment by lmgagne** [comment]
Here is the error I get:
`com.google.api.server.spi.SystemService invokeServiceMethod: exception occurred while calling backend method (SystemService.java:398)
java.lang.NullPointerException
	at us.raudi.pushraven.FcmResponse.getResponseCode(FcmResponse.java:32)
	at us.raudi.pushraven.FcmResponse.toString(FcmResponse.java:92)`

I used a fake device fcm id. Could this has anything to do? Is FCM doing some sort of device FCM id validation? If so, why would the push() method return a NPE?

**Comment by kubaguzik77** [comment]
Hello, 

I use Google App Engine (Standard Java Environment) and the same error occurs in my project. I am using version 1.0.2.

NullPointerException is thrown in line 32 of FcmResponse after I call FcmResponse.getResponseCode().

If it is a bug I'd also appreciate some fixes, because I did not manage to send any push notification from my server.

**Comment by Raudius** [comment]
I am not too familiar with the Google App Engine, but after delving into some of the Documentation I found this:

https://cloud.google.com/appengine/docs/standard/java/issue-requests

It seems that if you are under the "free quota" you must add the setting "urlfetch" to "appengine-web.xml", so it handles request-calls using the urlfetch methods.

If you are not under the "free quota" or using the Java 7 runtime, then there should be no issues using the native methods.


Although I am not at all familiar with how Google App Engine works, I hope this helps clear the issue.

**Comment by swellingt0n** [comment]
I am following the examples in this repo, and I am also unable to receive the notification on the device.

`Pushraven.setKey(FCM_SERVER_KEY);
		Notification raven = new Notification();

		// build raven message using the builder pattern
		raven.to(ANDROID_DEVICE_TOKEN).collapse_key("a_collapse_key").priority(1).delay_while_idle(true)
				.time_to_live(100).dry_run(true).data(getData()).title("Testing").body("Hello World!");
		// push the raven message
		FcmResponse response = Pushraven.push(raven);

		// prints response code and message
		System.out.println(response);`

With the following response:
Response: 200
Success Message: '{"multicast_id":-1,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"fake_message_id"}]}'
Error Message: ''

I have tried with both the current and legacy server keys from the console, and triggering the notifications from the console works.

**Comment by jeffmwells** [comment]
I had this same issue until i removed the `.dry_run(true)` call.

**Comment by Raudius** [comment]
@kubaguzik77 @lmgagne 

Can you let me know if you managed to fix the issue with the appengine-web.xml edit?

If not I will look into what else the issue might been.

**Comment by lmgagne** [comment]
I wrote a method that does an http call to the FCM url.
