### ISSUE TITLE
Web Push notification

### ISSUE THREAD

**Issue by mageshr2016** [Raudius/Pushraven#14]
Hi - thanks for this repo. It is very useful for me for android push notifications. Since FCM can be used for web push notification as well, I was wondering if this library could be used for that as well. Since it needs a server key, and the project in FCM seem to have only one server key, I was not sure how to use it for Web push. Pls throw some light on the same, as am bit new to this. Thanks for your help.

**Comment by Raudius** [comment]
There is no reason why you shouldn't be able to use it for Web Notifications. Afteral, all this library does is implement the FCM reference (https://firebase.google.com/docs/cloud-messaging/http-server-ref).

If you are using the same firebase project to send to Web and Mobile you might want to consider using 'topics' to  distinguish between different clients.
