### ISSUE TITLE
Allow passing InputStream for service account 

### ISSUE THREAD

**Issue by iamareebjamal** [Raudius/Pushraven#18]
Currently, only File is allowed to send to the PushRaven API

If the user is loading the JSON from environment variables, it is not feasible or secure to save that to a file and then provide to PushRaven

Secondly, files are not present in ephemeral file systems provided by services like Google App Engine and Heroku

Thirdly, a developer could have also loaded GoogleCredentials for personal use of Firebase in his app and reloading the InputStream for the same purpose inside Pushraven would be somewhat unnecessary

**Comment by Raudius** [comment]
Seems reasonable. Will add this to the next release.

Do you also know if GoogleAuth tokens are reusable? And to what point? 

As it stands Pushraven is making a new auth token for each push.

**Comment by iamareebjamal** [comment]
Yes they are reusable but calling `getAccessToken` is idempotent as it itself reuses the non-expired tokens and automatically refreshes them when expired so it is better to not cache it in the library itself

**Comment by Joni-Aaltonen** [comment]
Any news on the next release, would love to see this feature in

**Comment by Raudius** [comment]
Done! Thanks for the reminder!

It might take a few hours to get published on Maven Central.

You can find the jars in the Github release: https://github.com/Raudius/Pushraven/releases/tag/v2.1.0.2

**Comment by Raudius** [comment]
You can now set the GoogleCredential object directly through the static method:

```
GoogleCredential gcred = new GoogleCredential();
Pushraven.setCredential(gcred);
```

**Comment by Joni-Aaltonen** [comment]
Great thanks!
