### ISSUE TITLE
Can't get errors from getErrorMessage() 

### ISSUE THREAD

**Issue by ankonts** [Raudius/Pushraven#25]
When I send a deliberately incorrect request, I expect to receive an error. In the logs I see an error. But when I do getErrorMessage()  then there is no mistake.

Before the call getResponseCode() I see an error in the debug, but after it disappears

In log:
![image](https://user-images.githubusercontent.com/43990059/64409149-84116780-d0b2-11e9-9e59-f42bc80d4f00.png)

In debug:
![image](https://user-images.githubusercontent.com/43990059/64409240-b327d900-d0b2-11e9-8422-ccffb45c4d82.png)

**Comment by Raudius** [comment]
Thanks for reporting this. 

I have reworked the FcmResponse class, you can now access error and success messages using:
 `response.getMessage()`.

The new release (1.0.3) should be availalbe from the Maven repository in a few hours, the release is source and release is already on Github (https://github.com/Raudius/Pushraven/releases/latest)
