### ISSUE TITLE
i have a question to ask

### ISSUE THREAD

**Issue by Rekoe** [Raudius/Pushraven#5]
if i want send a message by the app package to broadcast .how can i do it?
whether it can send meessage only to ios or android ?

**Comment by Raudius** [comment]
You want to send notifications to all instances of the app package?

I'm not sure that its possible through FCM. With topics you may be able to achieve the same thing though.



> With Firebase Notifications and Cloud Messaging, you can send so-called downstream messages to devices in three ways:
> 
> to specific devices, if you know their device IDs
> to groups of devices, if you know the registration IDs of the groups
> to topics, which are just keys that devices can subscribe to

Source: http://stackoverflow.com/questions/38237559/how-do-you-send-a-firebase-notification-to-all-devices-via-curl/38248296#38248296

**Comment by Raudius** [comment]
There is also the "restricted_package_name" attribute, which may be useful though I have never used it myself. However it wont suffice on its own you may need to use it together with a "Topic".

**Comment by Rekoe** [comment]
ok thinks
