### ISSUE TITLE
Cannot find putAll method

### ISSUE THREAD

**Issue by OhhConti** [Raudius/Pushraven#6]
Hi, 
have you made an example or a tutorial? 
Because when I add your Notification.java class I get an error which says that  JSONObject.putAll method doesn't exist.

**Comment by Raudius** [comment]
You shouldn't get dependencies issues when using the release *.jar:
https://github.com/Raudius/Pushraven/releases/tag/v1.0.0

You can also download the org.simple.json dependency from:
https://code.google.com/archive/p/json-simple/downloads

**Comment by Raudius** [comment]
The only tutorials provided right now are the [Readme](https://github.com/Raudius/Pushraven/blob/master/README.md) and [Sample.java](https://github.com/Raudius/Pushraven/blob/master/Pushraven/src/com/pushraven/Sample.java)
