### ISSUE TITLE
Target User Segment?

### ISSUE THREAD

**Issue by robertofabrizi** [Raudius/Pushraven#7]
Dear developer, is it possible to target the user segment, like it can be done from the firebase website?
Thank you so much,
Roberto

**Comment by Raudius** [comment]
Unfortunately this is not yet possible to do through the HTTP API:
http://stackoverflow.com/questions/37371990/how-can-i-send-a-firebase-cloud-messaging-notification-without-use-the-firebase/37393535#37393535

Your best bet is to subscribe users to topics. And send notifications to these topics instead.

**Comment by robertofabrizi** [comment]
Ok thank you for your answer Raudius, and keep up your great work!

**Comment by robertofabrizi** [comment]
Dear @Raudius , I've waited for the topic to appear in firebase and used their console to test sending a message, which worked. Sadly it didn't work  with pushraven though. This is my code:

`public static void main(String[] args) {
		Pushraven.setKey(SERVER_KEY);
	
	        // create Notification object 
		Notification raven = new Notification();

        	HashMap<String, Object> data = new HashMap<String, Object>();
		data.put("Hello", "World!");
		data.put("Marco", "Polo");
		data.put("Foo", "Bar");
		
		// build raven message using the builder pattern
		raven.to("alarms")
        		//.collapse_key("alarms")
			.priority(1)
			//.delay_while_idle(true)
			.time_to_live(600)
			//.dry_run(true)
			.data(data)
			.title("Testing")
			.body("Hello World!")
			.color("#ff0000");
		
		// push the raven message
		FcmResponse response = Pushraven.push(raven);
		
		// prints response code and message
		System.out.println(response);
	}`

The output is 

> Response: 200
Message: ''

but nothing arrives on my phone....
