### ISSUE TITLE
Maven publication?

### ISSUE THREAD

**Issue by maxmumford** [Raudius/Pushraven#9]
I'm happily using this lil lib in production, works nicely, thanks! Any plans for Maven publication though? It makes deploying to platforms like Heroku much easier - I'd prefer not to have to commit your jar into VC.

Max

**Comment by Raudius** [comment]
I never originally intended this to be adopted by anyone bar myself for minor projects. But given the interest I will look into publishing it to a maven repo this weekend.

**Comment by maxmumford** [comment]
That would be fantastic, thanks. Of all of the FCM libs I've seen it has by far the most succinct API and configuration, so thanks for your work.

**Comment by Raudius** [comment]
I found some time to do it tonight. You should be able to add it as a dependency now using:

```
<dependency>
  <groupId>us.raudi.pushraven</groupId>
  <artifactId>Pushraven</artifactId>
  <version>1.0.1</version>
</dependency>
```

**Note that I had to change the package name to abide by the namespace allocation rules for the Central Repo. So you will have to change your imports to us.raudi.pushraven.***

**Comment by maxmumford** [comment]
Works a treat, thanks for your help :)
